#Fichier de configuration de FactionUtils

#Rayon de coordonnées minimum et maximum pour la commade /rtp
rtp:
  minRange: 2000
  maxRange: 50000
  

rate:
  #Le taux de drop du spawner si il est cassé par une pioche Silk Touch
  spawner: 0.5


cooldowns:
  #cooldown pour la commande rtp (en fonction des permissions)(en secondes)
  maitre: 60
  noble: 300
  citoyen: 6000
  
  #nombre d'utilisation des commandes par jour
  smelt: 5
  repair: 5
  